version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"  # Expose PostgreSQL on localhost:5432
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "librarydb" ]
      interval: 10s
      retries: 5
      start_period: 30s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-inventory-app
    depends_on:
      - postgres  # Wait until the Postgres container is ready
    ports:
      - "8080:8080"  # Expose your Spring Boot app on localhost:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/librarydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123

networks:
  app-network:
    driver: bridge
